"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateTitle = exports.generateChatResponse = exports.embedQuery = void 0;
var openai = require("./openai");
var gemini = require("./gemini");
var provider = process.env.LLM_PROVIDER;
var aiProvider = provider === 'openai' ? openai : gemini;
exports.embedQuery = aiProvider.embedQuery;
exports.generateChatResponse = aiProvider.generateChatResponse;
exports.generateTitle = aiProvider.generateTitle;
